#! /bin/sh

usage() {
    echo "Usage: $0 <path-to-source-file>";
    exit 1;
}

run_c() {
    gcc -o $filename.out $1;
    ./$filename.out;
}

run_cpp() {
    g++ -o $filename.out $1;
    ./$filename.out
}

run_python() {
    python3 $1;
}

run_kotlin() {
    kotlinc $1 -include-runtime -d $filename.jar;
    java -jar $filename.jar;
}

run_haskell() {
    # use haskell interpreter instead of compiling
    runhaskell $1;
}

run_scala() {
    # use scala interpreter instead of compiling
    scala $1;
}

if [ $# -ne 1 ]; then
    usage;
fi

if [ ! -f $1 ]; then
    echo "Error: $1 is not a file";
    usage;
fi

# Separate the filename from its extension
filename=$(basename $1);
extension="${filename##*.}";

case $extension in
    "c")
        run_c $1
        ;;
    "cpp")
        run_cpp $1
        ;;
    "py")
        run_python $1;
        ;;
    "kt")
        run_kotlin $1;
        ;;
    "hs")
        run_haskell $1;
        ;;
    "sc")
        run_scala $1;
        ;;
    *)
        echo "Unknown file type";
        ;;
esac
